### ISSUE TITLE
Failed to connect with 'host::' sometimes

### ISSUE THREAD

**Issue by GitCat3** [webadb/webadb.js#21]
so this only happens about half the time, but sometimes I will get the following error:
```
Uncaught (in promise) Error: Failed to connect with 'host::'
    at webadb.js:141:13
    at async HTMLButtonElement.submitForm (test.js:11:13)
```
all of the code can be found here: [the code](https://replit.com/@EthanMontellese/WebUSB-Test)
I am using a Nexus 5X for this experiment.

EDIT: Additionally, it seems that the adb command that I am running only returns to the console about half of the time as well.

**Comment by cavokz** [comment]
Therefore it seems that the problem is a lower level, right? What OS are you using? Can you reproduce this behavior on some other machine or OS or phone?

**Comment by GitCat3** [comment]
I am running this in the browser hosting platform that my code is in above, I could try running it on my windows computer.

**Comment by GitCat3** [comment]
So I ran it on my local device and it is still only working about half the time. This is now on my windows 10 machine, just opening the html file in chrome

**Comment by cavokz** [comment]
> So I ran it on my local device and it is still only working about half the time. This is now on my windows 10 machine, just opening the html file in chrome

And how `adb` behaves on your Windows 10 machine?

**Comment by GitCat3** [comment]
It works like normal

**Comment by cavokz** [comment]
Problem is I don't trust you enough to run your replit thing (incidentally I would have a Nexus 5X for trying it). Where are the sources of your application?

**Comment by GitCat3** [comment]
You should be able to view them by pressing on a thing that says files in the repl, but I'll attach the source here too. https://drive.google.com/drive/folders/1eW5wrjfCkvXQWmdT8NEMrxjSv0iW3H2r
